<?php
include_once("vars.php");
include_once("db_funcs.php");
include_once("db_build_tables_sql.php");
include_once("general_funcs.php");
include_once("verify_funcs.php");
include_once("index_funcs.php");
include_once("schedule_funcs.php");
include_once("users_funcs.php");
include_once("manage_funcs.php");
include_once("reports_funcs.php");
include_once("crc_funcs.php");
?>